# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 588f27b0ea27eba8f4c129c5c5d534422987bac532a05f44a8ab9436c7330cca65fc9e254b5ff980e1cb91c4a040f337ba5b5399decc1f971d81b61d26f6c61d

test:
  secret_key_base: ec04a32aaf8ba05c18fa06f30da7c5af0433b75875b7a01badf03defe2cd4a409c8d61fa6778d18664d756372d92c3aaa5fc409831b63740de7d7674dfe6a446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
